### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by dovydasgulbinas** [matas30rubliu/java-no-ide#1]
Could you please explain why is your github handle using a registered 30 Rubliu club trademark?

**Comment by matas30rubliu** [comment]
I will forward this to our team management, action item will be planned for the next sprint

**Comment by dovydasgulbinas** [comment]
> I will forward this to our team management, action item will be planned for the next sprint

Thank you for the swift response my only concern is that your legal team should be handling this issue. Thank you so much mister

Sincerely,
Shrek Swamp (CCO) at 30 Rubliu
